<?php

return [
    0 => [
        'id' => 0,
        'name' => '夸克',
        'domain' => 'pan.quark.cn',
        'cookie_key' => 'quark_cookie',
        'pan_type' => 'quark',
        'url_pattern' => '/https:\/\/pan\.quark\.cn\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'QuarkPan',
        'sort' => 1,
    ],
    1 => [
        'id' => 1,
        'name' => '阿里',
        'domain' => ['www.alipan.com', 'www.aliyundrive.com'],
        'cookie_key' => 'alipan_cookie',
        'pan_type' => 'alipan',
        'url_pattern' => '/https:\/\/(www\.alipan\.com|www\.aliyundrive\.com)\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'AlipanPan',
        'sort' => 2,
    ],
    2 => [
        'id' => 2,
        'name' => '百度',
        'domain' => 'pan.baidu.com',
        'cookie_key' => 'baidu_cookie',
        'pan_type' => 'baidu',
        'url_pattern' => '/https:\/\/pan\.baidu\.com\/s\/[a-zA-Z0-9_-]+(\?pwd=[a-zA-Z0-9]+)?/',
        'class_name' => 'BaiduPan',
        'sort' => 3,
    ],
    3 => [
        'id' => 3,
        'name' => 'UC',
        'domain' => ['drive.uc.cn', 'fast.uc.cn'],
        'cookie_key' => 'uc_cookie',
        'pan_type' => 'uc',
        'url_pattern' => '/https:\/\/drive\.uc\.cn\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'UcPan',
        'sort' => 4,
    ],
    4 => [
        'id' => 4,
        'name' => '迅雷',
        'domain' => 'pan.xunlei.com',
        'cookie_key' => 'xunlei_cookie',
        'pan_type' => 'xunlei',
        'url_pattern' => '/https:\/\/pan\.xunlei\.com\/s\/[a-zA-Z0-9_-]+(\?pwd=[a-zA-Z0-9]+)?/',
        'class_name' => 'XunleiPan',
        'sort' => 5,
    ],
    5 => [
        'id' => 5,
        'name' => '123',
        'domain' => ['123865.com', '123684.com', '123912.com', '123pan.com'],
        'cookie_key' => 'pan123_cookie',
        'pan_type' => 'pan123',
        'url_pattern' => '/https:\/\/123\d{3}\.com\/s\/[a-zA-Z0-9-]+/',
        'class_name' => 'Pan123Pan',
        'sort' => 6,
    ],
    6 => [
        'id' => 6,
        'name' => '115',
        'domain' => '115cdn.com',
        'cookie_key' => 'pan115_cookie',
        'pan_type' => 'pan115',
        'url_pattern' => '/https:\/\/115cdn\.com\/s\/[a-zA-Z0-9]+\?password=[a-zA-Z0-9]+/',
        'class_name' => 'Pan115Pan',
        'sort' => 7,
    ],
    7 => [
        'id' => 7,
        'name' => '天翼',
        'domain' => 'cloud.189.cn',
        'cookie_key' => 'tianyi_cookie',
        'pan_type' => 'tianyi',
        'url_pattern' => '/https:\/\/cloud\.189\.cn\/t\/[a-zA-Z0-9]+/',
        'class_name' => 'TianyiPan',
        'sort' => 8,
    ],
    8 => [
        'id' => 8,
        'name' => '移动',
        'domain' => 'caiyun.139.com',
        'cookie_key' => 'yidong_cookie',
        'pan_type' => 'yidong',
        'url_pattern' => '/https:\/\/caiyun\.139\.com\/m\/i\?[a-zA-Z0-9]+/',
        'class_name' => 'YidongPan',
        'sort' => 9,
    ],
    9 => [
        'id' => 9,
        'name' => '磁力',
        'domain' => '',
        'cookie_key' => '',
        'pan_type' => 'magnet',
        'url_pattern' => '/magnet:\?xt=urn:btih:[a-fA-F0-9]{40}(&[^&]+)*/',
        'class_name' => 'MagnetPan',
        'sort' => 10,
    ],
    10 => [
        'id' => 10,
        'name' => '光鸭',
        'domain' => 'www.guangyapan.com',
        'cookie_key' => 'guangya_cookie',
        'pan_type' => 'guangya',
        'url_pattern' => '/https:\/\/www\.guangyapan\.com\/s\/[a-zA-Z0-9_-]+/',
        'class_name' => 'GuangyaPan',
        'sort' => 11,
    ],
];
